# Generated by Django 5.1.5 on 2025-03-10 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preferences', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preferences',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
